### ISSUE TITLE
No compatible version found: babel-preset-es2015@0.6.0

### ISSUE THREAD

**Issue by DenVdmj** [PaulBernier/castl#5]
When i `npm install` i got the following err:

> ```
> npm ERR! No compatible version found: babel-preset-es2015@0.6.0
> npm ERR! Valid install targets:
> npm ERR! 6.6.0, 6.5.0, 6.5.0-1, 6.3.13, 6.2.4, 6.1.18, 6.1.17, 6.1.4, 6.1.2, 6.0.15, 6.0.14, 6.0.12, 6.0.11, 6.0.8, 6.0.2
> ```

With the line `"babel-preset-es2015": "6.6.0",` all installed successfully.

Offtopic: whether it is possible to use this tool to work livit? (ie for porting modules nodejs)
And thank you so much for wonderful perspective ))

**Comment by PaulBernier** [comment]
Thank you very much for reporting this, I don't know how I came to push that typo... Fixed by https://github.com/PaulBernier/castl/commit/c7fda7797a0cf33f24672c0029274d6aae93018e

I guess you meant Luvit? Hum Luvit is a pretty serious project and very optimized, I see CASTL more as a proof of concept for experimentation. But I guess you can kind of hack and try ;)

**Comment by DenVdmj** [comment]
Yes, "to work with Luvit", sorry ) When i look at how popular the js, get sad, that hardly ever lua can catchup js. So i think that even a small opportunity to simplify porting of packages is a very inspiring thing.
